config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  resources :contacts
  resources :relations, only: %i[show new create edit update destroy] do
    get 'contacts_without_relation', on: :collection
  end
  get 'eastereggs/curriculum'
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :user
  has_many :contact_relations, dependent: :destroy
  has_many :contacts, through: :contact_relations

  validates :relation_type, presence: true
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: %i[show edit update destroy]
  before_action :check_owner, only: %i[show edit update destroy]

  def show
    @contacts = @relation.contacts
    search_module
  end

  def new
    @relation = Relation.new
  end

  def create
    @relation = Relation.new(relation_params)
    @relation.user = current_user
    if @relation.save
      redirect_to edit_user_registration_path, notice: 'Relation created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @relation.update(relation_params)
    redirect_to edit_user_registration_path, notice: 'Relation updated'
  end

  def destroy
    @relation.destroy
    redirect_to edit_user_registration_path, notice: 'Relation deleted'
  end

  def contacts_without_relation
    @contacts = current_user.contacts
    @contacts = @contacts.left_outer_joins(:contact_relations).where(contact_relations: { id: nil })
    search_module
  end

  private

  def search_module
    @contacts = @contacts.search_by_name(params[:query]) if params[:query].present?
    respond_to do |format|
      format.html
      format.text { render partial: 'contacts/list', locals: { contacts: @contacts }, formats: [:html] }
    end
  end

  def check_owner
    unless @relation.user == current_user
      flash[:alert] = "This relationship is not yours."
      redirect_back fallback_location: root_path
    end
  end

  def set_relation
    @relation = Relation.find(params[:id])
  end

  def relation_params
    params.require(:relation).permit(:relation_type)
  end
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/relations/_form.html.erb
<div class="container mt-3 mb-3 d-flex flex-column align-items-center">
  <%= simple_form_for @relation do |f| %>
    <%= f.input :relation_type, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
    <div>
      <%= button_tag(type: 'submit', class: 'btn btn-grey') do %>
        <i class="fa-solid fa-check"></i> OKay
      <% end %>
    </div>
  <% end %>
</div>

app/views/relations/_index.html.erb
<%= link_to raw('<i class="fa-solid fa-bullseye""></i> Add new'), new_relation_path, class: 'mt-4 btn btn-grey' %>

<ul class='mt-4 container'>
  <% relations.each do |relation| %>
    <li class='card-text row'>
    <%= link_to relation_path(relation), class:'col-8 nav-link' do %>
      <%= relation.relation_type %> <%= "(#{relation.contacts.count} contacts)"%>
    <% end %>
      <%= link_to '🎨', edit_relation_path(relation), class:'no-underline col-2' %>
      <%= link_to '💣', relation_path(relation), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently delete #{relation.relation_type} ? It will also be deleted from the contact records." }, class:'no-underline col-2'  %>
    </li>
  <% end %>
  <% if contacts_without_relation.present? %>
    <li class="card-text row">
      <%= link_to contacts_without_relation_relations_path, class:'nav-link' do %>
        <%= "Undefined relationships  (#{contacts_without_relation.count})" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/relations/contacts_without_relation.html.erb
<div class="container mt-3 mb-3">
  <div class="position-relative">
    <h1 class="position-absolute top-0 start-50 translate-middle-x title w-100">Contacts without relationship defined (<%= @contacts.count %> contacts)</h1>
    <br>
    <div data-controller='auto-search'>
      <div class="d-flex justify-content-between mt-5 ">
        <%# Bouton mobile %>
          <%= link_to raw('<i class="fa-solid fa-chevron-left"></i>'), edit_user_registration_path,
          class:'d-md-none btn btn-grey-square', rel: 'prefetch' %>
        <%# Bouton desktop %>
          <%= link_to raw('<i class="fa-solid fa-chevron-left"></i> Back'), edit_user_registration_path,
          class:'d-none d-md-flex btn btn-grey align-items-baseline pt-2 gap-2', rel: 'prefetch' %>

        <%= form_tag contacts_path, method: :get, class: "d-flex gap-1" do %>
          <%= text_field_tag :query, params[:query], data: { action: 'keyup->auto-search#update', auto_search_target: 'input' }, class: "form-control front-input", placeholder: "Search by name, address..." %>
          <%= button_tag type: 'button', class: 'btn btn-grey-square' do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <% end %>
        <% end %>
      </div>
      <br>
      <%= render 'contacts/list', contacts: @contacts %>
    </div>
  </div>
</div>

app/views/relations/edit.html.erb
<%= render 'form', relation: @relation %>

app/views/relations/index.html.erb
<div class="container mt-3">
  <h1>All your relation types (<%= @relations.count %>)</h1>
  <%= link_to '➕ Add new relation', new_relation_path %>

  <ul>
    <% @relations.each do |relation| %>
      <li>
        <%= relation.relation_type %>
        <%= link_to '🎨 Edit', edit_relation_path(relation) %>
        <%= link_to '💣 Delete', relation_path(relation), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently delete #{relation.relation_type} ? It will also be deleted from the contact records." }  %>
      </li>
    <% end %>
  </ul>
</div>

app/views/relations/new.html.erb
<%= render 'form', relation: @relation %>

app/views/relations/show.html.erb
<div class="container mt-3 mb-3">
  <div class="position-relative">
    <h1 class="position-absolute top-0 start-50 translate-middle-x title w-100"><%= @relation.relation_type %> (<%= @relation.contacts.count %>)</h1>
    <br>
    <div data-controller='auto-search'>
      <div class="d-flex justify-content-between mt-4">
        <%# Bouton mobile %>
          <%= link_to raw('<i class="fa-solid fa-chevron-left"></i>'), edit_user_registration_path,
          class:'d-md-none btn btn-grey-square', rel: 'prefetch' %>
        <%# Bouton desktop %>
          <%= link_to raw('<i class="fa-solid fa-chevron-left"></i> Back'), edit_user_registration_path,
          class:'d-none d-md-flex btn btn-grey me-auto d-flex align-items-baseline pt-2 gap-2', rel: 'prefetch' %>

        <%= form_tag contacts_path, method: :get, class: "d-flex gap-1" do %>
          <%= text_field_tag :query, params[:query], data: { action: 'keyup->auto-search#update', auto_search_target: 'input' }, class: "form-control front-input", placeholder: "Search by name, address..." %>
          <%= button_tag type: 'button', class: 'btn btn-grey-square' do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <% end %>
        <% end %>
      </div>
      <br>
      <%= render 'contacts/list', contacts: @relation.contacts %>
    </div>
  </div>
</div>