config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  resources :contacts
  resources :relations, only: %i[show new create edit update destroy] do
    get 'contacts_without_relation', on: :collection
  end
  get 'eastereggs/curriculum'
end

app/models/contact.rb
class Contact < ApplicationRecord
  include PgSearch::Model
  has_one_attached :photo

  belongs_to :user
  has_many :contact_relations, dependent: :destroy
  has_many :relations, through: :contact_relations

  validates :first_name, presence: true

  pg_search_scope :search_by_name,
                  against: %i[first_name last_name phone_number address birthday],
                  ignoring: :accents,
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]
  before_action :check_owner, only: %i[show edit update destroy]

  def index
    @contacts = current_user.contacts.order(:last_name)
    @contacts = @contacts.search_by_name(params[:query]) if params[:query].present?
    respond_to do |format|
      format.html
      format.text { render partial: 'contacts/list', locals: { contacts: @contacts }, formats: [:html] }
    end
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user
    if @contact.save
      redirect_to contacts_path, notice: 'Contact created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @contact.update(contact_params)
    redirect_to contact_path(@contact), notice: 'Contact updated'
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path, notice: 'Contact deleted'
  end

  private

  def check_owner
    unless @contact.user == current_user
      flash[:alert] = "This contact is not yours."
      redirect_back fallback_location: root_path
    end
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :photo, :phone_number, :address, :birthday, :note, relation_ids: [])
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%# New & edit contact form %>

<div class="container mt-3 mb-3 d-flex justify-content-center">
  <%= simple_form_for @contact, html: { class: 'd-flex flex-column mt-3 gap-3' } do |f| %>
    <div class='d-flex gap-3'>
      <%= f.input :first_name, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
      <%= f.input :last_name, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
    </div>
    <%= f.input :photo, as: :file, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
    <div class='d-flex gap-3'>
      <%= f.input :phone_number, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
      <%= f.input :address, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
    </div>
    <div class='d-flex gap-3'>
      <%= f.input :birthday, as: :string, input_html: { data: { controller: 'datepicker' }, class: 'front-input'}, label_html: { class: 'font-label' } %>
      <%= f.association :relations, collection: current_user.relations, label_method: :relation_type, prompt: "Select relation",
                                    multiple: true, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
    </div>
    <%= f.input :note, input_html: { class: 'front-input'}, label_html: { class: 'font-label' } %>
    <div class="form-actions d-flex justify-content-center">
      <%= button_tag(type: 'submit', class: 'btn btn-grey') do %>
        <i class="fa-solid fa-check"></i> Okay
      <% end %>
    </div>
  <% end %>

app/views/contacts/_list.html.erb
<div data-auto-search-target="list" class='d-flex flex-wrap'>
  <% if contacts.present? %>
    <% contacts.each do |contact| %>
      <div class="card contact-card">
        <div class="btn-group dropup">
          <button type="button" class="dropdown-toggle btn btn-grey-square transparant" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu menu-radius">
            <li><%= link_to '🎨 Edit', edit_contact_path(contact), class: "dropdown-item choice-menu no-underline" %></li>
            <li><%= link_to '💣 Delete', contact_path(contact), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently delete #{contact.first_name} ?" }, class: "dropdown-item choice-menu no-underline" %></li>
          </ul>
        </div>
        <%= link_to contact_path(contact) do %>
          <% if contact.photo.attached? %>
            <%= cl_image_tag contact.photo.key, gravity: :face, height: 450, width: 450, crop: :fill, class: "card-img-top" %>
          <% else %>
            <%= image_tag("photo_not_yet_available.jpg", class: "card-img-top", alt: "contact picture") %>
          <% end %>
          <div class="card-body d-flex justify-content-center">
            <p class="card-text"><%= contact.first_name %> <%= contact.last_name %></p>
          </div>
        <% end %>
      </div>
    <% end %>

  <% else %>
    <h1 class='title mt-3'>No contacts found :(</h1>
  <% end %>
</div>

<%# !EASTEREGG BELOW %>
  <%# Modals %>
    <div class="modal fade" id="editModal" tabindex="+1" aria-labelledby="editModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editModalLabel">This is my CV !</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>And no one can edit my life 😉</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-grey" data-bs-dismiss="modal">Sorry !</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="+1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">This is my CV !</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>So please do not delete me 😨</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-grey" data-bs-dismiss="modal">Sorry !</button>
          </div>
        </div>
      </div>
    </div>

  <%# Curriculum card %>
    <div data-auto-search-target="hidden" class='d-none d-flex flex-wrap'>
      <div class="card contact-card">
        <div class="btn-group dropup">
          <button type="button" class="dropdown-toggle btn btn-grey-square transparant" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu menu-radius">
            <button type="button" class="dropdown-item choice-menu no-underline" data-bs-toggle="modal" data-bs-target="#editModal">
              🎨 Edit
            </button>
            <button type="button" class="dropdown-item choice-menu no-underline" data-bs-toggle="modal" data-bs-target="#deleteModal">
              💣 Delete
            </button>
          </ul>
        </div>
        <%= link_to eastereggs_curriculum_path do %>
            <%= image_tag("CV.jpg", class: "card-img-top", alt: "contact picture") %>
          <div class="card-body d-flex justify-content-center">
            <p class="card-text">Flavien LERAY</p>
          </div>
        <% end %>
      </div>
    </div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<div class="container mt-3 mb-3">
  <h1 class="title">My contacts book (<%= @contacts.count %> contacts)</h1>
  <br>
  <div data-controller='auto-search'>
    <div class="d-flex justify-content-between align-items-center gap-1">
      <%# Bouton mobile%>
      <%= link_to raw('<i class="fa-solid fa-user-plus"></i>'), new_contact_path, class: "d-md-none btn btn-grey-square btn-add" %>
      <%# Bouton desktop%>
      <%= link_to raw('<i class="fa-solid fa-user-plus"></i> Add new contact'), new_contact_path, class: "d-none d-md-flex btn btn-grey btn-add" %>

      <%= form_tag contacts_path, method: :get, class: "d-flex gap-1" do %>
        <%= text_field_tag :query, params[:query], data: { action: 'keyup->auto-search#update', auto_search_target: 'input' }, class: "form-control front-input", placeholder: "Search by name, address..." %>
        <%= button_tag type: 'button', class: 'btn btn-grey-square' do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
    </div>
    <br>
    <%= render 'list', contacts: @contacts %>
  </div>
</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<div class="container mt-3 mb-3 d-flex flex-column align-items-center position-relative">
    <%# Bouton mobile %>
      <%= link_to raw('<i class="fa-solid fa-chevron-left"></i>'), (request.referer || contacts_path),
        class:'d-md-none btn btn-grey-square me-auto sticky', rel: 'prefetch' %>
    <%# Bouton desktop %>
      <%= link_to raw('<i class="fa-solid fa-chevron-left"></i> Back'), (request.referer || contacts_path),
        class:'d-none d-md-flex btn btn-grey sticky me-auto d-flex align-items-baseline pt-2 mt-1 gap-2', rel: 'prefetch' %>

  <div class='position-absolute d-flex gap-3 align-items-center justify-content-center'>
    <h1 class='title'><%= @contact.first_name %> <%= @contact.last_name %></h1>
    <div class="dropdown">
      <button type="button" class="dropdown-toggle btn btn-grey-square" data-bs-toggle="dropdown" aria-expanded="false"></button>
      <ul class="dropdown-menu menu-radius">
        <li><%= link_to '🎨 Edit', edit_contact_path(@contact), class: "dropdown-item choice-menu no-underline" %></li>
        <li><%= link_to '💣 Delete', contact_path(@contact), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently delete #{@contact.first_name} ?" }, class: "dropdown-item choice-menu no-underline" %></li>
      </ul>
    </div>
  </div>

  <%# Mobile display : %>
    <div class="d-md-none">
      <div class="<%= 'mt-5' if @contact.photo.attached? %>">
        <% if @contact.photo.attached? %>
          <%= cl_image_tag @contact.photo.key, gravity: :face, height: 400, width: 400, crop: :fill, class: "img-fluid", style: 'border-radius: 15px;' %>
        <% end %>

        <div class="infos <%= @contact.photo.attached? ? "mt-4" : "mt-5" %>">
          <div data-controller="clipboard">
            <p class='font-label mt-1 mb-0'>Phone number :</p>
            <div class='d-flex align-items-baseline gap-3'>
              <p data-clipboard-target="source" class='text background'><%= @contact.phone_number %></p>
              <% if @contact.phone_number.present? %>
                <button data-action="clipboard#copy" data-clipboard-target="button" class='btn btn-grey-square'><i class="fa-regular fa-clipboard"></i></button>
              <% end %>
            </div>
          </div>

          <div data-controller="clipboard">
            <p class='font-label mt-1 mb-0'>Address :</p>
            <div class='d-flex align-items-baseline gap-3'>
              <%= simple_format(@contact.address, data: { clipboard_target: "source" }, class: 'text background') %>
              <% if @contact.address.present? %>
                <button data-action="clipboard#copy" data-clipboard-target="button" class='btn btn-grey-square'><i class="fa-regular fa-clipboard"></i></button>
              <% end %>
            </div>
          </div>

          <div data-controller="clipboard">
            <p class='font-label mt-1 mb-0'>Date of birth :</p>
            <div class='d-flex align-items-baseline gap-3'>
              <p data-clipboard-target="source" class='text background'><%= @contact.birthday.strftime('%b %e, %Y') if @contact.birthday%></p>
              <% if @contact.birthday.present? %>
                <button data-action="clipboard#copy" data-clipboard-target="button" class='btn btn-grey-square'><i class="fa-regular fa-clipboard"></i></button>
              <% end %>
            </div>
          </div>

          <div class='d-flex gap-4'>
            <p class='font-label mt-1 mb-0'>Relationship :</p>
            <div class='d-flex align-items-baseline gap-3 mt-1'>
              <ul class='text background'>
                <% @contact.relations.each do |relation| %>
                  <li><%= relation.relation_type %></li>
                <% end %>
              </ul>
            </div>
          </div>

          <div data-controller="clipboard" class='d-flex flex-column mt-1'>
            <p class='font-label mb-0'>Personal notes :</p>
            <div class='d-flex flex-column gap-3 mt-1'>
              <%= simple_format(@contact.note, data: { controller: 'read-more', action: 'read_more#connect', read_more_target: 'text', clipboard_target: "source" }, class: 'add-read-more show-less-content text background mb-0') %>
              <% if @contact.note.present? %>
                <button data-action="clipboard#copy" data-clipboard-target="notice" class='btn btn-grey d-flex align-items-center gap-2 align-self-center p-2'>
                <p class='mb-0'>Copy</p>
                <i class="fa-regular fa-clipboard"></i>
              <% end %>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%# End of mobile display %>

  <%# Desktop display : %>
    <div class="<%= 'gap-4 d-none d-md-flex' if @contact.photo.attached? %>">
      <div class="image mt-5">
        <% if @contact.photo.attached? %>
          <%= cl_image_tag @contact.photo.key, gravity: :face, height: 400, width: 400, crop: :fill, style: 'border-radius: 15px;' %>
        <% end %>
      </div>

      <div class="infos mt-5">
        <div data-controller="clipboard" class='d-none d-md-flex align-items-baseline mt-3 gap-3'>
          <p class='font-label'>Phone number :</p>
          <p data-clipboard-target="source" class='text background'><%= @contact.phone_number %></p>
          <% if @contact.phone_number.present? %>
            <button data-action="clipboard#copy" data-clipboard-target="button" class='btn btn-grey-square'><i class="fa-regular fa-clipboard"></i></button>
          <% end %>
        </div>

        <div data-controller="clipboard" class='d-none d-md-flex align-items-baseline mt-3 gap-3'>
          <p class='font-label'>Address :</p>
          <%= simple_format(@contact.address, data: { clipboard_target: "source" }, class: 'text background') %>
          <% if @contact.address.present? %>
            <button data-action="clipboard#copy" data-clipboard-target="button" class='btn btn-grey-square'><i class="fa-regular fa-clipboard"></i></button>
          <% end %>
        </div>

        <div data-controller="clipboard" class='d-none d-md-flex align-items-baseline mt-3 gap-3'>
          <p class='font-label'>Date of birth :</p>
          <p data-clipboard-target="source" class='text background'><%= @contact.birthday.strftime('%b %e, %Y') if @contact.birthday%></p>
          <% if @contact.birthday.present? %>
            <button data-action="clipboard#copy" data-clipboard-target="button" class='btn btn-grey-square'><i class="fa-regular fa-clipboard"></i></button>
          <% end %>
          <p class='font-label'>Relationship :</p>
          <ul class='text background'>
            <% @contact.relations.each do |relation| %>
              <li><%= relation.relation_type %></li>
            <% end %>
          </ul>
        </div>

        <div data-controller="clipboard" class='d-none d-md-flex flex-column mt-3'>
          <p class='font-label'>Personal notes :</p>
          <%= simple_format(@contact.note, data: { controller: 'read-more', action: 'read_more#connect', read_more_target: 'text', clipboard_target: "source" }, class: 'add-read-more show-less-content text background') %>
          <% if @contact.note.present? %>
            <button data-action="clipboard#copy" data-clipboard-target="notice" class='btn btn-grey d-flex align-items-center gap-2 align-self-center p-2'>
            <p class='mb-0'>Copy</p>
            <i class="fa-regular fa-clipboard"></i>
          <% end %>
          </button>
        </div>
      </div>
    </div>
  <%# End of desktop display %>
</div>